################
# Nelly Amenyogbe
# Function:  get features selected from a mixomics sPLS-DA object
#################

# This function is written to provide a data frame listing the features selected by sPLS-DA (implemented in mixOmics V6) for a given component of the model.

# Input ####

# mixomics.obj = splsda object, generated by the function mixOmics::splsda()
# comp =  component of interest (e.g. comp.1)

# Output ####
# data.frame; includes name of feature, loading along selected component, and the ablsolute value of the loading score, ordered from highest to lowest based on absolute value

mc.get.features <- function(mixomics.obj, comp){
  
  # get loadings from mixomics object
  loadings <- data.frame(mixomics.obj$loadings$X)
  loadings$feature <- rownames(loadings)
  
  # modify data frame to only include comp of interest
  loadings <- loadings[,c("feature", comp)]
  loadings$raw.loadings <- loadings[,2]
  
  # add absolute loadings and order features by strength
  loadings$abs.loadings <- abs(loadings$raw.loadings)
  loadings <- loadings[order(loadings$abs.loadings, decreasing = TRUE),]
  
  # remove redundant column
  loadings <- loadings[,-2]
  return(loadings)
  
}